### ISSUE TITLE
Replication of results

### ISSUE THREAD

**Issue by inderjeetnair** [nlpaueb/multi-eurlex#1]
Hello, Thanks for sharing the code. I wanted to know the argument values for reproducing the results in the paper "LEGAL-BERT: The Muppets straight out of Law School". I tried executing the code in its default setting (`eval_langs` was set to `['en']`). This resulted in a very poor performance. I am attaching the log file with this message (
[MULTI-EURLEX_2022_01_19_05_01_19.txt](https://github.com/nlpaueb/multi-eurlex/files/7894317/MULTI-EURLEX_2022_01_19_05_01_19.txt)). Thanks.

**Comment by iliaschalkidis** [comment]
Hi @Inderbat,

I guess you did not change any default argument values, which means that the code will just load 10 train/dev/test samples, which is only useful for debugging the code 😄 

https://github.com/nlpaueb/multi-eurlex/blob/8e4486b17e309a974dbf29b824d91efc66264e59/experiments/trainer.py#L43-L44

In order to reproduce the results, you have to set both parameters to `False` in order to load the full dataset.

This repo will help you reproduce the results of our recent publication [MultiEURLEX – A multi-lingual and multi-label legal document classification dataset for zero-shot cross-lingual transfer](https://aclanthology.org/2021.emnlp-main.559.pdf), which uses a newer, multi-lingual, larger, and harder version of the original EUR-LEX dataset.


If you wish to reproduce the results of LEGAL-BERT on the standard EUR-LEX dataset, you'll have to use this repo (https://github.com/iliaschalkidis/lmtc-eurlex57k), although I strongly recommend re-using this newer version of the code and the dataset, which can be used for English only experiments (if you're not interested in other languages). Given the default arguments, you'll train XLM-R on the English subset.

Please let me know if you have further questions, and mark the issue resolved.

**Comment by inderjeetnair** [comment]
Thanks for the prompt answer. I overlooked the functionality of these arguments 😢.
